"""create submissions table

Revision ID: 57fdd1bcf63e
Revises: 
Create Date: 2026-08-09 20:23:36.880358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fdd1bcf63e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leetcode_submission_id', sa.String(length=100), nullable=False),
    sa.Column('problem_slug', sa.String(length=200), nullable=False),
    sa.Column('problem_title', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('github_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_leetcode_submission_id'), 'submissions', ['leetcode_submission_id'], unique=True)
    op.create_index(op.f('ix_submissions_problem_slug'), 'submissions', ['problem_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_problem_slug'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_leetcode_submission_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
